import { config } from 'dotenv';
config();

import '@/ai/flows/compliance-recommendations.ts';
import '@/ai/flows/attendance-flow.ts';
import '@/ai/flows/process-daily-attendance.ts';
import '@/ai/flows/generate-offer-letter.ts';
import '@/ai/flows/run-payroll-flow.ts';
import '@/ai/flows/support-chat-flow.ts';
import '@/ai/flows/handle-application-flow.ts';
import '@/ai/flows/report-emergency-flow.ts';
import '@/ai/flows/submit-training-flow.ts';
import '@/ai/flows/request-leave-flow.ts';
import '@/ai/flows/generate-contract-flow.ts';
import '@/ai/flows/submit-resignation-flow.ts';
import '@/ai/flows/process-job-closures.ts';
import '@/ai/flows/post-guest-job-flow.ts';
import '@/ai/flows/add-manual-applicant-flow.ts';
import '@/ai/flows/reject-applicant-flow.ts';
import '@/ai/flows/send-email-flow.ts';
import '@/ai/flows/create-campaign-flow.ts';
import '@/ai/flows/logged-in-guest-job-flow.ts';
import '@/ai/flows/upgrade-guest-account-flow.ts';
import '@/ai/flows/import-employees-flow.ts';
